"""init db

Revision ID: cbe6ef8fa2bc
Revises: 
Create Date: 2023-07-03 17:38:21.599064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe6ef8fa2bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    op.create_table('khata_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('farmer_name', sa.String(length=100), nullable=False),
    sa.Column('crop_kind', sa.String(length=100), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('farm_area', sa.Float(), nullable=False),
    sa.Column('billed_amount', sa.Float(), nullable=False),
    sa.Column('date_of_activity', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('khata_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_khata_entry_lender_id'), ['lender_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lender_id', sa.Integer(), nullable=False),
    sa.Column('khata_entry_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['khata_entry_id'], ['khata_entry.id'], ),
    sa.ForeignKeyConstraint(['lender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_lender_id'), ['lender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_lender_id'))

    op.drop_table('payment')
    with op.batch_alter_table('khata_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_khata_entry_lender_id'))

    op.drop_table('khata_entry')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))

    op.drop_table('user')
    # ### end Alembic commands ###
